---
# Stage 1: Ansible playbook
- name: Provision app host with Docker and containers
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      tags: ["bootstrap"]

    - name: Ensure community.docker collection is installed system-wide (root)
      ansible.builtin.command: ansible-galaxy collection install community.docker -p /usr/share/ansible/collections
      args:
        creates: "/usr/share/ansible/collections/ansible_collections/community/docker"
      tags: ["bootstrap", "collections"]

    - name: Ensure community.docker collection is installed for vagrant user
      become_user: vagrant
      ansible.builtin.command: ansible-galaxy collection install community.docker -p ~/.ansible/collections
      args:
        creates: "/home/vagrant/.ansible/collections/ansible_collections/community/docker"
      tags: ["bootstrap", "collections"]

  roles:
    - { role: common, tags: ["common", "bootstrap"] }
    - { role: app_repo, tags: ["app", "repo"] }
    - { role: database, tags: ["db"] }
    - { role: backend, tags: ["backend"] }
    - { role: frontend, tags: ["frontend"] }
