---
frontend_build_context: "{{ app_base_dir }}/frontend"
frontend_dockerfile: "Dockerfile"
frontend_image_name: "okoth-frontend:latest"
frontend_container_name: "brian-yolo-client"
frontend_port: 3000
frontend_env: {}
